# Generated by Django 5.2 on 2025-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0002_alter_user_email_alter_user_username_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['end_time']},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_end_tim_b53b8a_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_time', 'end_time'], name='appointment_start_t_7965c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time'), name='unique_appointment_slot'),
        ),
    ]
